In [1]:
import pandas as pd
import numpy as np

In [31]:
# Q1. Write a function `fibonacci(n)` that generates the first `n` numbers in the Fibonacci sequence and return
def fibonacci(n):

  f1 = 0
  f2 = 1
  if (n < 1):
        return
  print(f1, end=" ")
  for x in range(1, n):
        print(f2, end=" ")
        next = f1 + f2
        f1 = f2
        f2 = next

fibonacci(7)

TypeError: 'tuple' object is not callable

In [32]:
 #Q . Write a function `is_prime(num)` that checks if a given number is a prime number. Return `True` if the number is prime

def is_prime(n):
    i = 2

    if n in (1,3):
        return True
    elif n == 2:
        return False

    while i <= n//2:
        if n%i != 0:
            return True
        else:
            return False
        i+=1

for x in range(1, 5):
  print(x, '=', is_prime(x))

TypeError: 'tuple' object is not callable

In [88]:
#Q . Write a function `is_prime(num)` that checks if a given number is a prime number. Return `True` if the number is prime

def is_prime(n):
    i = 2

    if n in (1,3):
        return True
    elif n == 2:
        return False

    while i <= n//2:
        if n%i != 0:
            return True
        else:
            return False
        i+=1

is_prime(12)

False

In [89]:
is_prime(5)

True

In [ ]:
# Q Using the dataset provided below, perform the following tasks. The dataset contains information about a company

In [36]:
data = {
 'Date': ['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04', '2024-01-05'],
 'Sales': [200, 220, 210, 215, 225],
 'Region': ['North', 'South', 'East', 'West', 'North'],
 'Manager': ['John', 'Jane', 'Joe', 'Jake', 'John']
}

In [37]:
#Q 1. Load the dataset into a pandas DataFrame and display its first 5 rows
s = pd.DataFrame(data) #loading data in the dataframe using pandas
s.head() #diplaying top 5 rows using head function

         Date  Sales Region Manager
0  2024-01-01    200  North    John
1  2024-01-02    220  South    Jane
2  2024-01-03    210   East     Joe
3  2024-01-04    215   West    Jake
4  2024-01-05    225  North    John

In [46]:
#Q 2. Add a new column `Profit` which is 10% of the `Sales` column.

s['Profit']=s['Sales']*1.0
s

         Date  Sales Region Manager  Profit
0  2024-01-01    200  North    John   200.0
1  2024-01-02    220  South    Jane   220.0
2  2024-01-03    210   East     Joe   210.0
3  2024-01-04    215   West    Jake   215.0
4  2024-01-05    225  North    John   225.0

In [41]:
#Q Group the data by `Region` and calculate the total sales for each region.

s.groupby('Region').sum('Sales') #calculating total sales by gruoping region

        Sales
Region
East      210
North     425
South     220
West      215

In [81]:
# Q Find the region with the highest average sales.
a=s.groupby('Region')['Sales'].mean() # calculating the avg sales by grouping region
b=a.idxmax() # finding region with highest avg sales
c=a.max() # highest avg sales

print('region with highest average sales is ',b ,'with average salary',c)

TypeError: 'tuple' object is not callable

In [83]:
# Q Find the region with the highest average sales.
a=s.groupby('Region')['Sales'].mean() # calculating the avg sales by grouping region
region_with_highest_average_sales=a.idxmax() # finding region with highest avg sales
highest_average_sales=a.max() # highest avg sales

In [84]:
region_with_highest_average_sales

'South'

In [85]:
highest_average_sales

220.0

In [53]:
 # Q . Load a CSV file from a GitHub repository into a pandas DataFrame. Use the following URL

In [54]:
ds=pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
ds

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [55]:
#Q  Display the first 5 rows of the DataFrame. (1 Mark)
ds.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [56]:
# Q 2. Display summary statistics of the DataFrame. (1 Mark)
print(ds.describe())

TypeError: 'tuple' object is not callable

In [57]:
ds.describe()# displaying statistical summary of dataset

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [58]:
 # Q 3. Check for null values in the DataFrame and display the count of null values in each column. (1 Mark)
ds.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [59]:
 #Q 4. Fill the null values in the 'Age' column with the mean age. (1 Mark)
m_age=ds['Age'].mean() # calculating the maen value of the age col
ds['Age'].fillna(m_age) # filling the null valuse of age cols with the mean value i.e. "m_age"
ds

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [62]:
# Q 5. Drop the rows where 'Embarked' is null. (1 Mark)
ds.dropna(subset=['Embarked'], inplace=True) #droped all the rows which contain null values in embarked col
ds

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [66]:
ds.isnull().sum() # here now there is no null values ib embarked col

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [68]:
# Q 6. Create a new column 'FamilySize' which is the sum of 'SibSp' and 'Parch'. (1 Mark)
ds['familysize']=ds['SibSp']+ds['Parch'] # creating new col with the sum of sibsp, parch cols
ds

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,familysize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0

In [70]:
# Q 7. Convert the 'Sex' column to numerical values (male: 0, female: 1). (1 Mark)
ds['Sex']=ds['Sex'].map({'male': 0, 'female':1}) # converting the males and females of sex column in to integer value
ds

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,familysize
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.0,0,0,211536,13.0000,NaN,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.0,0,0,112053,30.0000,B42,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,NaN,1,2,W./C. 6607,23.4500,NaN,S,3
889,890,1,1,"Behr, Mr. Karl Howell",0,26.0,0,0,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",0,32.0,0,0,370376,7.7500,NaN,Q,0

In [71]:
# Q8. Group the data by 'Pclass' and calculate the average fare for each class. (1 Mark)
a = ds.groupby('Pclass')['Fare'].mean() # calculating mean value of fare col by grouping pclass col
a

Pclass
1    84.193516
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [74]:
# Q 9. Find the most common port of embarkation ('Embarked' column). (1 Mark)
ds['Embarked'].mode()[0] # commom port pf embarked col using mode method

'S'

In [78]:
#Q 10. Create a pivot table that shows the survival rate ('Survived') for each combination of 'Sex' and 'Pclass'
plot=pd.pivot_table(ds,values='Survived',index='Sex', columns='Pclass',aggfunc='mean') # pivot plot of survival rate
plot

Pclass         1         2         3
Sex
0       0.368852  0.157407  0.135447
1       0.967391  0.921053  0.500000